<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>SISCAD-WEB</title>

    <link rel="stylesheet" href="<?php echo $url ?>/public/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="<?php echo $url ?>/public/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="<?php echo $url ?>/public/css/styles.css">
    <script src="public/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
  <body>
    <div id="content">
      <div class="page-header">
        <h1>SISCAD-WEB <br><small>Login</small></h1>
      </div>
        <div id="form-login" >
        <form method="post" action="<?php echo $url ?>/login">
          <div class="input-group form-siscad">
            <label>Usuário
              <input type="text" class="form-control" placeholder="usuário" name="nome">
            </label>
          </div>

          <div class="input-group form-siscad">
            <label>Senha
              <input type="password" class="form-control" placeholder="senha" name="senha">
            </label>
          </div>

          <div class="input-group form-siscad">
            <input type="submit" class="btn btn-success" />
          </div>
        </form>
      </div>

    </div>
  </body>
</html>
