<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>SISCAD-WEB</title>
    <link rel="stylesheet" href="<?php echo $url ?>/public/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $url ?>/public/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="<?php echo $url ?>/public/css/styles.css">
    <script src="public/js/bootstrap.min.js"></script></head>
  <body>
    <div id="content">
      <div class="page-header">
        <h1>SISCAD-WEB <br><small>Lista de acesso ao SISCAD-API</small></h1>
        <div id="logout"><a href="<?php echo $url ?>/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Sair</a></div>

      </div>
      <h3><a href="<?php echo $url ?>/usuario/novo"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Novo usuário</a></h3>
      <ul class="list-group">
      <?php foreach ($userList as $user) { ?>
        <li class="list-group-item"><a href='<?php echo $url ?>/usuario/editar/<?php echo $user->getId(); ?>'><?php echo $user->getNome(); ?> <span class="glyphicon glyphicon-pencil" aria-hidden="true"></a></li>
      <?php } ?>
      </ul>
    </div>
  </body>
</html>
