<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>SISCAD-WEB</title>

    <link rel="stylesheet" href="<?php echo $url ?>/public/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="<?php echo $url ?>/public/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="<?php echo $url ?>/public/css/styles.css">
    <script src="public/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
  <body>
    <div id="content">
      <div class="page-header">
        <h1>SISCAD-WEB <br><small>Lista de acesso ao SISCAD-API</small></h1>
        <div id="logout"><a href="<?php echo $url ?>/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Sair</a></div>

      </div>
      <h3><a href="<?php echo $url ?>/usuario/novo"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Novo usuário</a></h3>
      <ul class="list-group">
      <?php foreach ($userList as $user) { ?>
        <li class="list-group-item"><a href='<?php echo $url ?>/usuario/editar/<?php echo $user->getId(); ?>'><?php echo $user->getNome(); ?> <span class="glyphicon glyphicon-pencil" aria-hidden="true"></a></li>
      <?php } ?>
      </ul>
    </div>
  </body>
</html>
